#!/bin/bash

# --- VCF Preparation and Annotation Workflow ---
# This script prepares VCFs and runs SnpSift (ClinVar) and SnpEff annotation.

set -o pipefail
set -o errexit
set -u

echo "--- Starting VCF Annotation Workflow ---"

# --- 1. Configuration (CENSORED PLACEHOLDERS) ---
# VCFs generated by 01_data_extraction.py
GCS_VCF_SOURCE_BUCKET="gs://<YOUR_SECURE_BUCKET>/CMP_Gene_Data/VCF_Format"

# Local directories
VCF_DIR_IN_LOCAL="${BASE_DIR}/vcf_input"  # Directory to download VCFs into
OUTPUT_DIR="${BASE_DIR}/annot"            # Directory for annotated VCFs

mkdir -p "$VCF_DIR_IN_LOCAL"
mkdir -p "$OUTPUT_DIR"

# --- Tool Paths (Sourced from 03_software_setup.sh) ---
# NOTE: These variables must be sourced/exported before running this script.
JAVA="${PATH_JAVA:-/usr/bin/java}"             # Default to system java if variable is missing
SNPSIFT_JAR="${PATH_SNPSIFT_JAR:-snpEff/SnpSift.jar}"
SNPEFF_JAR="${PATH_SNPEFF_JAR:-snpEff/snpEff.jar}"
CLINVAR_VCF="${PATH_CLINVAR_GZ:-clinvar.vcf.gz}"
# Assuming snpEff.config is in the same directory as snpEff.jar
SNPEFF_CONFIG="$(dirname $SNPEFF_JAR)/snpEff.config"
SNPEFF_DB="hg38" 


# --- 2. Download VCF Files from GCS ---
echo "Copying VCF files from GCS to local VM: $VCF_DIR_IN_LOCAL"
gsutil cp -r "${GCS_VCF_SOURCE_BUCKET}"/*.bgz "$VCF_DIR_IN_LOCAL"
cd "$VCF_DIR_IN_LOCAL"


# --- 3. VCF Header Fix (For SnpSift Compatibility) ---
# Decompress, fix headers (empty Description fields), and re-compress/move to annotation directory.

echo "--- 3. Fixing VCF Headers and Decompressing ---"

for f_gzipped in *.vcf.bgz; do
    [ -e "$f_gzipped" ] || continue
    
    vcf_file_raw="${f_gzipped%.bgz}"
    
    # Decompress and Fix Header: replace empty INFO Description="" with a placeholder
    bgzip -d -c "$f_gzipped" | \
    sed 's/##INFO=<\(ID=[^,]*\),Number=[^,]*,Type=[^,]*,Description="">/##INFO=<\1,Number=.,Type=String,Description="Description not provided">/' \
    > "$vcf_file_raw"
    
    echo "Fixed header for: $vcf_file_raw"
done

# Clean up compressed files and move to annotation target directory
rm -f *.vcf.bgz

# --- 4. Sequential Annotation (ClinVar + SnpEff) ---

echo "--- 4. Running ClinVar (SnpSift) and Functional (SnpEff) Annotation ---"

for vcf_file in *.vcf; do
    [ -e "$vcf_file" ] || continue

    # Step 4.1: ClinVar annotation using SnpSift
    clinvar_annot="${OUTPUT_DIR}/$(basename "${vcf_file%.vcf}").clinvar.vcf"
    echo "Annotating ${vcf_file} with ClinVar..."
    # Placeholder command reflecting SnpSift logic: $JAVA -jar $SNPSIFT_JAR ann -v $CLINVAR $VCF > $OUTPUT
    "$JAVA" -jar "$SNPSIFT_JAR" ann -v "$CLINVAR_VCF" "$vcf_file" > "$clinvar_annot"

    # Step 4.2: SnpEff annotation
    final_annot="${OUTPUT_DIR}/$(basename "${vcf_file%.vcf}").annot.vcf"
    echo "Annotating ${clinvar_annot} with SnpEff..."
    # Placeholder command reflecting SnpEff logic: $JAVA -jar $SNPEFF_JAR -c $CONFIG -v $DB $CLINVAR_VCF > $FINAL_OUTPUT
    "$JAVA" -jar "$SNPEFF_JAR" -c "$SNPEFF_CONFIG" -v $SNPEFF_DB "$clinvar_annot" > "$final_annot"

    # Clean up intermediate file
    rm -f "$clinvar_annot"

    echo "Final annotated VCF saved to: $final_annot"
done

echo "Annotation pipeline complete."